apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-runner
  template:
    metadata:
      labels:
        app: gh-runner
    spec:
      containers:
        - name: main
          image: myoung34/github-runner:2.311.0
          env:
            - name: ACCESS_TOKEN
              value: 
            - name: REPO_URL
              value: "https://github.com/0hyeon/airflow"
            - name: RUNNER_SCOPE
              value: "repo"
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc